### PR TITLE
print to stdout instead

### PR DESCRIPTION
**Pull request by Accacio**
printing to stdout we can use it in scripts and pipe to other programs, or redirect to a file

### CODE REVIEW

**Comment by umgefahren** [comment]
To be honest I don’t really see the point. This is just a CLI for standalone use of the underlying libraries.
The libraries could be used directly instead over going over the CLI.
I will merge, when you describe why your change has a direct advantage over using the libraries.

**Comment by Accacio** [comment]
Well, usually it is just a rule of thumb when using plain text. Many programs like curl do this, Other users don't necessarily use rust and sometimes they just want to change the output piping the results to other programs, e.g.: grep, nl etc

For instance, if someone wants a recipe book, one could just run
`for i in ~/cook/*.cook; do cook-with-rust recipe -s $i markdown >> myrecipes.md; done`

**Comment by umgefahren** [comment]
I think I see your point. As a compromise, what do you think of the following:
If one wants output to stdout, you just leave the path argument empty. I will modify the code the code that way, if you thinks is a solid solution.
In general the application of the CLI should not be in scripts. I just wanted to build a utility that implements about the same features as the Swift implementation.
Piping content over system io is not really fast, so it should be avoided in my mind. Because it's in Rust I could easily add a FFI for other languages. Python bindings over pyo3 would be very easy.
However I appreciate the input and would implement the requested feature if you want to. You could also do it yourself, if you want.

**Comment by spencerpogo** [comment]
> Piping content over system io is not really fast, so it should be avoided in my mind.

I don't think it is slow enough to not use, but regardless of performance, this is a common standard for CLIs. Personally, I think it makes sense in this case and allows more flexibility in scripts. If you want people to use the library, why make the CLI part?

**Comment by Accacio** [comment]
Usually use a -o option to choose an output file

**Pull request closed without merging**
